-- What is the total revenue generated by make vs female customers? 

SELECT 
    gender, 
    sum(purchase_amount) as total_revenue
FROM customer

GROUP BY
    gender

ORDER BY
    total_revenue DESC
